
export const POSTS = {
  POSTS: 'POSTS',
  POSTS_REQUEST: 'POSTS_REQUEST',
  POSTS_RECEIVE: 'POSTS_RECEIVE',
  STATUS_CLEAR: 'STATUS_CLEAR',
  POST_UPDATE: 'POST_UPDATE',
  POST_CREATE: 'POST_CREATE',
  POST_DELETE: 'POST_DELETE',
  POSTS_LIST: 'POSTS_LIST',
  COMMENTS_GET: 'COMMENTS_GET',
  COMMENTS_LIST: 'COMMENTS_LIST'
};
