
export const POSTS = {
  POSTS_REQUEST: 'POSTS_REQUEST',
  POSTS_RECEIVE: 'POSTS_RECEIVE',
  POST_UPDATE: 'POST_UPDATE',
  POST_CREATE: 'POST_CREATE',
  POST_DELETE: 'POST_DELETE',

  USERS_REQUEST: 'USERS_REQUEST',
  USERS_RECEIVE: 'USERS_RECEIVE',

  COMMENTS_REQUEST: 'COMMENTS_REQUEST',
  COMMENTS_RECEIVE: 'COMMENTS_RECEIVE'
};
